import api from './api'

export const challengeService = {
  // get all challenges
  getChallenges: async () => {
    return api.get('/challenges/')
  },

  // get one challenge by its real database ID
  getChallengeById: async (id) => {
    return api.get(`/challenges/${id}`)
  },

  // submit a new challenge
  submitChallenge: async (payload) => {
    return api.post('/challenges/', payload)
  },

  // get AI analysis for a challenge
  getAIAnalysis: async (challengeId) => {
    return api.get(`/challenges/${challengeId}/ai-analysis`)
  },

  // get HEI matches generated by the backend
  getHEIMatches: async (challengeId) => {
    return api.get(`/challenges/${challengeId}/hei-matches`)
  },

    // get faculty matches generated by the backend
  getFacultyMatches: async (challengeId) => {
    return api.get(`/challenges/${challengeId}/faculty-matches`)
  },
}