import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { MapPin, FileText, Sparkles, UserCheck } from 'lucide-react'
import Badge from '../../components/common/Badge'
import Card from '../../components/common/Card'
import { challengeService } from '../../services/challengeService'
import { heiService } from '../../services/heiService'

export default function ChallengeDetailPage() {
  const { id } = useParams()

  const [challenge, setChallenge] = useState(null)
  const [aiAnalysis, setAiAnalysis] = useState(null)
  const [heiMatches, setHeiMatches] = useState([])
  const [heiDetails, setHeiDetails] = useState({})
  const [facultyMatches, setFacultyMatches] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const loadChallenge = async () => {
      try {
        setLoading(true)
        setError('')

        // get the real challenge from our backend
        const challengeResponse =
          await challengeService.getChallengeById(id)

        // get the AI analysis generated for this challenge
        const aiResponse =
          await challengeService.getAIAnalysis(id)

        // get the HEI matches generated by our matcher
        const matchesResponse =
          await challengeService.getHEIMatches(id)

        // get the faculty matches generated by our matcher
        const facultyResponse =
          await challengeService.getFacultyMatches(id)

        setChallenge(challengeResponse.data)
        setAiAnalysis(aiResponse.data)
        setHeiMatches(matchesResponse.data)
        setFacultyMatches(facultyResponse.data)

        // get the actual HEI names for the recommendations
        const details = {}

        await Promise.all(
          matchesResponse.data.map(async (match) => {
            try {
              const heiResponse =
                await heiService.getHEIById(match.hei_id)

              details[match.hei_id] = heiResponse.data
            } catch (err) {
              console.error(`Could not load HEI ${match.hei_id}`, err)
            }
          })
        )

        setHeiDetails(details)
      } catch (err) {
        console.error(err)

        setError(
          err.response?.data?.detail ||
            'Could not load challenge details.'
        )
      } finally {
        setLoading(false)
      }
    }

    loadChallenge()
  }, [id])

  if (loading) {
    return (
      <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center">
        <p className="text-slate-600">
          Loading challenge details...
        </p>
      </div>
    )
  }

  if (error || !challenge) {
    return (
      <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center">
        <p className="text-red-600">
          {error || 'Challenge not found.'}
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
            Challenge
          </p>

          <h1 className="mt-2 text-3xl font-bold text-slate-900">
            {challenge.title}
          </h1>
        </div>

        <Badge status={challenge.status} />
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        <Card title="Challenge overview">
          <div className="space-y-5 text-sm text-slate-600">
            <p>{challenge.description}</p>

            <div className="grid gap-3 sm:grid-cols-2">
              <div className="rounded-xl bg-slate-50 p-3">
                <span className="block text-xs uppercase tracking-[0.15em] text-slate-500">
                  Domain
                </span>

                <span className="mt-2 block text-base font-semibold text-slate-900">
                  {challenge.category}
                </span>
              </div>

              <div className="rounded-xl bg-slate-50 p-3">
                <span className="block text-xs uppercase tracking-[0.15em] text-slate-500">
                  Priority
                </span>

                <span className="mt-2 block text-base font-semibold text-slate-900">
                  {challenge.priority_score}/100
                </span>
              </div>

              <div className="rounded-xl bg-slate-50 p-3">
                <span className="block text-xs uppercase tracking-[0.15em] text-slate-500">
                  Challenge ID
                </span>

                <span className="mt-2 block text-base font-semibold text-slate-900">
                  #{challenge.id}
                </span>
              </div>

              <div className="rounded-xl bg-slate-50 p-3">
                <span className="block text-xs uppercase tracking-[0.15em] text-slate-500">
                  Submitted date
                </span>

                <span className="mt-2 block text-base font-semibold text-slate-900">
                  {new Date(
                    challenge.created_at
                  ).toLocaleDateString()}
                </span>
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 p-4">
              <div className="mb-3 flex items-center gap-2 text-slate-700">
                <MapPin className="h-4 w-4" />
                Location details
              </div>

              <div className="text-sm text-slate-600">
                {[
                  challenge.locality,
                  challenge.block,
                  challenge.district,
                ]
                  .filter(Boolean)
                  .join(', ') || 'Location not provided'}
              </div>
            </div>
          </div>
        </Card>

        <Card title="Evidence">
          <div className="space-y-3 text-sm text-slate-600">
            <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3">
              <FileText className="h-4 w-4 text-slate-500" />
              Evidence upload will be connected next.
            </div>
          </div>
        </Card>
      </div>

      <Card title="AI analysis">
        <div className="grid gap-4 md:grid-cols-3">
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-sm text-slate-500">
              <Sparkles className="h-4 w-4" />
              Category
            </div>

            <div className="mt-3 text-xl font-bold text-slate-900">
              {aiAnalysis?.category || challenge.category}
            </div>

            <div className="mt-1 text-sm text-slate-600">
              Confidence:{' '}
              {aiAnalysis?.category_confidence
                ? `${Math.round(
                    aiAnalysis.category_confidence * 100
                  )}%`
                : 'N/A'}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-sm text-slate-500">
              <UserCheck className="h-4 w-4" />
              Priority
            </div>

            <div className="mt-3 text-xl font-bold text-slate-900">
              {aiAnalysis?.priority_score ??
                challenge.priority_score}
            </div>

            <div className="mt-1 text-sm text-slate-600">
              out of 100
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-sm text-slate-500">
              <Sparkles className="h-4 w-4" />
              Duplicate status
            </div>

            <div className="mt-3 text-xl font-bold text-slate-900">
              {aiAnalysis?.is_duplicate ? 'Yes' : 'No'}
            </div>

            {aiAnalysis?.duplicate_score !== null &&
              aiAnalysis?.duplicate_score !== undefined && (
                <div className="mt-1 text-sm text-slate-600">
                  Similarity: {aiAnalysis.duplicate_score}
                </div>
              )}
          </div>
        </div>
      </Card>

      <Card title="Recommended universities">
        <div className="grid gap-4 lg:grid-cols-2">
          {heiMatches.map((match) => {
            const hei = heiDetails[match.hei_id]

            return (
              <div
                key={match.id}
                className="rounded-2xl border border-slate-200 bg-slate-50 p-4"
              >
                <div className="flex items-center justify-between gap-3">
                  <h3 className="text-lg font-semibold text-slate-900">
                    {hei?.name || `HEI #${match.hei_id}`}
                  </h3>

                  <span className="rounded-full bg-slate-900 px-2.5 py-1 text-xs font-semibold text-white">
                    Match Score: {match.match_score}%
                  </span>
                </div>

                <p className="mt-3 text-sm text-slate-600">
                  Why this university?
                </p>

                <p className="mt-2 text-sm text-slate-600">
                  {match.match_reason ||
                    'Recommended based on expertise and infrastructure.'}
                </p>
              </div>
            )
          })}
        </div>
      </Card>

      <Card title="Recommended faculty">
        {facultyMatches.length === 0 ? (
          <p className="text-sm text-slate-600">
            No matching faculty found for this challenge.
          </p>
        ) : (
          <div className="grid gap-4 lg:grid-cols-2">
            {facultyMatches.map((faculty) => (
              <div
                key={faculty.faculty_id}
                className="rounded-2xl border border-slate-200 bg-slate-50 p-4"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h3 className="text-lg font-semibold text-slate-900">
                      {faculty.faculty_name}
                    </h3>

                    <p className="mt-1 text-sm text-slate-600">
                      {faculty.designation || 'Faculty'}
                    </p>
                  </div>

                  <span className="rounded-full bg-slate-900 px-2.5 py-1 text-xs font-semibold text-white">
                    {faculty.match_score}% Match
                  </span>
                </div>

                <div className="mt-4 space-y-1 text-sm text-slate-600">
                  <p>
                    <span className="font-medium text-slate-800">
                      University:
                    </span>{' '}
                    {faculty.hei_name || 'N/A'}
                  </p>

                  <p>
                    <span className="font-medium text-slate-800">
                      Department:
                    </span>{' '}
                    {faculty.department_name || 'N/A'}
                  </p>
                </div>

                <p className="mt-3 text-sm text-slate-600">
                  {faculty.match_reason}
                </p>

                <div className="mt-3 text-xs font-semibold text-slate-500">
                  Rank #{faculty.rank}
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  )
}