"""add hei association to users

Revision ID: 340802efadca
Revises: dc0d42e44d94
Create Date: 2026-09-07 14:17:38.927092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340802efadca'
down_revision: Union[str, Sequence[str], None] = 'dc0d42e44d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hei_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'heis', ['hei_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hei_id')
    # ### end Alembic commands ###
