"""add challenge location fields

Revision ID: 3bccd21c0db7
Revises: 340802efadca
Create Date: 2026-09-07 14:59:50.544249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bccd21c0db7'
down_revision: Union[str, Sequence[str], None] = '340802efadca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('challenges', sa.Column('block', sa.String(length=100), nullable=True))
    op.add_column('challenges', sa.Column('locality', sa.String(length=200), nullable=True))
    op.add_column('challenges', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'longitude')
    op.drop_column('challenges', 'latitude')
    op.drop_column('challenges', 'locality')
    op.drop_column('challenges', 'block')
    op.drop_column('challenges', 'district')
    # ### end Alembic commands ###
