"""add scientist reviews

Revision ID: 9cdd699d6acf
Revises: 651a1ba331a4
Create Date: 2026-09-08 20:50:34.494350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cdd699d6acf'
down_revision: Union[str, Sequence[str], None] = '651a1ba331a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scientist_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('scientist_id', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expertise_area', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['scientist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientist_reviews_id'), 'scientist_reviews', ['id'], unique=False)
    op.drop_index(op.f('ix_project_impact_id'), table_name='project_impact')
    op.drop_table('project_impact')
    op.drop_index(op.f('ix_project_deliverables_id'), table_name='project_deliverables')
    op.drop_table('project_deliverables')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_table('project_deliverables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_deliverables_project_id_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('project_deliverables_submitted_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_deliverables_pkey'))
    )
    op.create_index(op.f('ix_project_deliverables_id'), 'project_deliverables', ['id'], unique=False)
    op.create_table('project_impact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_benefited', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('villages_covered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('districts_covered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cost_savings', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('environmental_impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deployment_status', sa.VARCHAR(length=30), server_default=sa.text("'NOT_DEPLOYED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_impact_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_impact_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('project_impact_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_project_impact_id'), 'project_impact', ['id'], unique=False)
    op.drop_index(op.f('ix_scientist_reviews_id'), table_name='scientist_reviews')
    op.drop_table('scientist_reviews')
    # ### end Alembic commands ###
