"""create hei departments table

Revision ID: afd1ed61b5ef
Revises: 5346113047a7
Create Date: 2026-09-05 22:55:17.150716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd1ed61b5ef'
down_revision: Union[str, Sequence[str], None] = '5346113047a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hei_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hei_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hei_id'], ['heis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hei_departments_id'), 'hei_departments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hei_departments_id'), table_name='hei_departments')
    op.drop_table('hei_departments')
    # ### end Alembic commands ###
