"""add industry collaborations

Revision ID: dc0d42e44d94
Revises: 1e7971b3fe29
Create Date: 2026-09-06 19:15:11.483435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0d42e44d94'
down_revision: Union[str, Sequence[str], None] = '1e7971b3fe29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('industry_user_id', sa.Integer(), nullable=False),
    sa.Column('support_type', sa.String(length=30), nullable=False),
    sa.Column('funding_amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_collaborations_id'), 'industry_collaborations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_collaborations_id'), table_name='industry_collaborations')
    op.drop_table('industry_collaborations')
    # ### end Alembic commands ###
