"""add industry collaborations

Revision ID: f09273927bfb
Revises: add_sms_notifications
Create Date: 2026-09-09 13:07:56.139681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f09273927bfb'
down_revision: Union[str, Sequence[str], None] = 'add_sms_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_impact')
    op.drop_index(op.f('ix_project_deliverables_id'), table_name='project_deliverables')
    op.drop_table('project_deliverables')
    op.alter_column('sms_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('project_deliverables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_deliverables_project_id_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('project_deliverables_submitted_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_deliverables_pkey'))
    )
    op.create_index(op.f('ix_project_deliverables_id'), 'project_deliverables', ['id'], unique=False)
    op.create_table('project_impact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_benefited', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('villages_covered', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('districts_covered', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_savings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('environmental_impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deployment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_impact_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_impact_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('project_impact_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
